FROM ghcr.io/actions/actions-runner:2.315.0
LABEL org.opencontainers.image.source=https://github.com/synapsestudios/meat-runner

SHELL ["/bin/bash", "--login", "-c"]
WORKDIR /home/runner
USER root
# apt-fast prerequisites
RUN apt-get update && apt-get install -y software-properties-common; rm -rf /var/lib/apt/lists/*
# Install apt-fast
RUN add-apt-repository ppa:apt-fast/stable
RUN apt-get update && apt-get install -y apt-fast
RUN echo "alias apt-get='apt-fast --no-install-recommends'" >> /root/.bashrc
RUN source /root/.bashrc

RUN apt-get install -y curl
RUN apt-get install -y unzip
RUN apt-get install -y openjdk-17-jdk
RUN apt-get install -y gradle
RUN apt-get install -y npm

ARG NVM_VERSION=0.39.7
ARG NODE_VERSIONS="18 20 21"
# Switch back to runner user to install nvm
USER runner
SHELL ["/bin/bash", "--login", "-i", "-o", "pipefail", "-c"]
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v${NVM_VERSION}/install.sh | bash
RUN source $HOME/.bashrc
# Install Node LTS
RUN nvm install --lts
RUN for version in $NODE_VERSIONS; do nvm install $version; done
RUN nvm use --lts
SHELL ["/bin/bash", "--login", "-c"]
CMD ["/home/runner/run.sh"]