name: PR Build

on:
  pull_request:
    branches:
      - main

jobs:
  create_matrix:
    uses: ./.github/workflows/create_matrix.yml
    with:
      image_directory: "./images"

  build:
    runs-on: ubuntu-latest
    needs: create_matrix
    strategy:
      matrix:
        image_folder: ${{fromJson(needs.create_matrix.outputs.matrix)}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Image Name output
        run: echo "image_name=$(python3 -c "print('${{ matrix.image_folder }}'.split('/')[0])")" >> $GITHUB_OUTPUT
        id: set_image_name

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t ${{ steps.set_image_name.outputs.image_name }}:latest ${{ matrix.image_folder }}/.

      - name: Check build status
        run: docker run --rm ${{ steps.set_image_name.outputs.image_name }}:latest
